### ISSUE TITLE
There's a specific date mixed up in the programme's closing days

### ISSUE THREAD

**Issue by biqiguhexuenai** [UweTrottmann/SeriesGuide#1036] opened 2024-07-21 13:09 UTC
There's a specific date mixed up in the programme's closing days.
I don't know why this is happening, it seems to only show up in the Tower of the Gods after 7 days
![IMG_20240721_210800](https://github.com/user-attachments/assets/3b64c255-255d-4794-8169-decc2626c2c2)

**Comment by UweTrottmann** [comment] 2024-07-25 13:42
Thanks for reporting! Could you give me the TMDB links for those shows so I can reproduce?

**Comment by biqiguhexuenai** [comment] 2024-07-25 14:14
> Thanks for reporting! Could you give me the TMDB links for those shows so I can reproduce?

OK
[seriesguide-shows-backup.json](https://github.com/user-attachments/files/16379000/seriesguide-shows-backup.json)

**Comment by UweTrottmann** [comment] 2024-08-09 14:35
Turns out: it displays relative time ("in 7 days") when the release date is within exactly 1 week or less. In this case, the last episode is released in 1 week plus a few hours. So the date is displayed (2024-07-28) instead of relative time.

This is working as intended.

**Closed by UweTrottmann** 2024-08-09 14:35 UTC
Labels: bug, needs-info
