### ISSUE TITLE
[Feature Request] Go to movie/series directly by pasting link

### ISSUE THREAD

**Issue by yephny** [UweTrottmann/SeriesGuide#840] opened 2022-02-06 11:25 UTC
I noticed I cannot find Stalker (1979) by searching up its name. I tried searching with the year it was released, no results. I tried searching for its number on TMDB, 1398, didn't work. Well, neither does pasting a TMDB link in the search bar.

Being able to use tmdb links to go to movies (and pasting them into the search bar) would make sure that the user can find whatever movie they want.

**Comment by UweTrottmann** [comment] 2022-02-09 12:27
Thanks, duplicate of #740

**Closed by UweTrottmann** 2022-02-09 12:27 UTC
