### ISSUE TITLE
Dealing with the new popup menu

### ISSUE THREAD

**Issue by GreyAsteroid** [UweTrottmann/SeriesGuide#518] opened 2017-05-14 04:15 UTC
Regarding the new popup menu displayed after pressing the tick icon; please consider removing it, adding an option to disable it, or making the popup menu only show up after long pressing the tick icon. 

The default action for the tick icon since it's creation has been setting an episode as watched and the addition of this popup menu does nothing more but add an extra step to the process of doing this.

Myself and from what I can tell many other users do not use the "check in" or even the entire collections features meaning that it really does absolutely nothing but add an extra step to what used to be a 1 button process. 

I'd also like to point out that "set watched" isn't even the first item on the popup menu making it really easy to accidentally press the wrong menu item since it's between two others.

I personally don't update all the episodes I've seen right after I've seen them meaning that when I do enter the app I'm planning on setting quite a lot of episodes as watched and this popup menu quite frankly makes it a really annoying pain in the butt. It doesn't help that the popup menu actually covers up the next episode that I want to set as watched so I have to search for the icon again and try not to be too fast or else oops I just added it to my collection.

I'll also point out that when I opened the app today to set episodes as watched I managed to accidentally add an episode to my unused collection because I pressed the tick icon expecting it to do what it's always done but instead causing the popup menu to show up over the next tick icon I wanted to press causing "add to collection" to be selected instead. 

I can go on and on about how much I absolutely despise this feature and want it to burn if you need more motivation to kill it. Though trying to be a bit more level headed, I think it would just be a better idea if you made the popup menu show up on long press of the tick icon instead of changing the default action that icon has had since I believe forever.

**Comment by UweTrottmann** [comment] 2017-05-17 08:10
Thanks for the feedback on your use case. In the next update check-in will be the last option and only visible if connected to trakt.

Closing, as this is not a bug.

**Closed by UweTrottmann** 2017-05-17 08:10 UTC

**Comment by UweTrottmann** [comment] 2017-05-17 08:29
Update: will probably revert to old behavior. See [my comment in the community](https://plus.google.com/+SeriesGuideApp/posts/B5cGXyPN8L9).
