### ISSUE TITLE
Add shows to the user's Trakt watchlist

### ISSUE THREAD

**Issue by smiley** [UweTrottmann/SeriesGuide#457] opened 2015-04-25 15:16 UTC
SeriesGuide doesn't have an option to add shows to the watchlist, and my shows list is too big already to add all these shows I come across but can't watch now. Can you add support for it? Maybe to the left of the +/check in the Add Show menu? (but with a small margin to prevent muscle memory errors)

**Comment by UweTrottmann** [comment] 2015-04-27 14:32
Duplicate of https://github.com/UweTrottmann/SeriesGuide/issues/188.

Again, I also defer to the https://seriesguide.uservoice.com/forums/189742-general/suggestions/3526390-add-tv-show-to-trakt-watchlist suggestion on UserVoice. You might want to vote for it!

**Closed by UweTrottmann** 2015-04-27 14:32 UTC
